name: Create Env File

on:
  workflow_call:
    inputs:
      port:
        required: true
        type: string
      hello_message:
        required: true
        type: string

jobs:
  create-env:
    runs-on: ubuntu-latest

    steps:
    - name: Create .env file
      run: |
        echo HELLO_MESSAGE=${{ inputs.hello_message }} >> .env
        echo PORT=${{ inputs.port }} >> .env

    - name: Persist .env file
      uses: actions/upload-artifact@v3
      with:
        name: env-file
        path: .env