name: Auto Deploy on Dev

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

  test:
    runs-on: self-hosted
    needs: checkout
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Create test env-file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_HELLO_MESSAGE: ${{ secrets.HELLO_MESSAGE }}
          envkey_PORT: ${{ secrets.PORT }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          directory: ./
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  
  close_pr_on_failure:
  runs-on: self-hosted
  needs: test
  if: failure()
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Close pull request
      run: gh pr close ${{ github.event.pull_request.number }} -r "Closing PR due to failed tests."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build:
    runs-on: self-hosted
    needs: [checkout, test]
    environment: dev
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Create dev env-file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_HELLO_MESSAGE: ${{ secrets.HELLO_MESSAGE }}
          envkey_PORT: ${{ secrets.PORT }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false
          directory: ./
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build --if-present

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Restart Application with PM2
        run: |
          npm run deploy:up