on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, dev]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
      with:
        path: dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: pm2 restart ./dist/main.js