name: Auto Deploy on Dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]  # Adjust based on your project's Node.js version requirement
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env file
        env:
          ENVIRONMENT: dev
          PORT: ${{ secrets.PORT }}
          HELLO_MESSAGE: ${{ secrets.HELLO_MESSAGE }}
        run: |
          echo "HELLO_MESSAGE=$HELLO_MESSAGE" > .env
          echo "PORT=$PORT" >> .env

      - run: |
          echo "HELLO_MESSAGE: $HELLO_MESSAGE"

      - run: npm ci

      - run: npm run build --if-present

      - run: pm2 restart main