name: Auto Deploy on Dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  create-env:
    runs-on: [self-hosted, dev]

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      env:
        PORT: ${{ secrets.PORT }}
        HELLO_MESSAGE: '${{ secrets.HELLO_MESSAGE }}'
      run: |
        echo "HELLO_MESSAGE=\"$HELLO_MESSAGE\"" >> .env
        echo "PORT=$PORT" >> .env

    - name: Persist .env file
      uses: actions/upload-artifact@v3
      with:
        name: env-file
        path: .env

    environment:
      name: dev

  build:
    runs-on: [self-hosted, dev]
    needs: create-env

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - run: npm run build --if-present

  deploy:
    runs-on: [self-hosted, dev]
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Download .env file
      uses: actions/download-artifact@v3
      with:
        name: env-file

    - run: pm2 restart main